[project]
name = "alert-mind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "fastapi>=0.136.3",
    "langchain-milvus>=0.3.3",
    "loguru>=0.7.3",
    "pydantic-settings>=2.14.1",
    "pymilvus>=2.5.0,<3.0.0",
    "uvicorn>=0.48.0",
]
